version: '3.1'

services:
  payment_gateway.datastore:
      container_name: payment_gateway.datastore
      image: mongo:4.2
      ports:
        - 27018:27017
      restart: always

  bank_simulator:
      container_name: bank_simulator
      build:
        context: ./simulator/
        dockerfile: Dockerfile
      ports:
          - 49160:8080